apiVersion: apps/v1
kind: Deployment
metadata:
  name: anhinga
  namespace: anhinga-namespace
  labels:
    app: anhinga
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anhinga
  template:
    metadata:
      labels:
        app: anhinga
    spec:
      nodeSelector:
        role: worker
      containers:
      - name: anhinga
        image: ghcr.io/drewpypro/anhinga:v1.0.2
        ports:
        - containerPort: 80