apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: anhinga-virtual-service
  namespace: anhinga-namespace
spec:
  hosts:
    - anhinga.drewpy.pro
  gateways:
    - istio-system/ingress-gateway
  http:
      - route:
        - destination:
            host: anhinga
            port:
              number: 80